name: Generate Allure Report

on:
  push:
    branches:
      - master
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Install Allure Command Line
        run: |
          # Download and install Allure CLI
          curl -o allure.tar.gz -Ls https://github.com/allure-framework/allure2/releases/latest/download/allure-$([ "$(uname)" = "Linux" ] && echo "linux" || echo "windows").zip
          unzip allure.tar.gz -d /tmp/
          sudo mv /tmp/allure /usr/bin/
          sudo chmod +x /usr/bin/allure
          allure --version  # Verify Allure installation

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report
